"""B2 — the OpenAI-compatible adapter (Contract B, spec/20).

One class for every provider that speaks OpenAI's `/v1/chat/completions`, which is all of them
except Anthropic: **Groq, OpenAI, xAI, DeepSeek, Mistral, OpenRouter** and **Google**'s compat
layer in the cloud, plus **Ollama, LM Studio and llama.cpp** locally. What differs between them
is a base URL and a credential, and both come from the catalogue
(`shared/schemas/settings.json`, hard rule 3) — so this is one adapter, not nine.

That is also why spec/20's B2 row was widened rather than a fourth row added (D30): "local
OpenAI-compatible server" and "cloud OpenAI-compatible API" were never two pieces of code.

    python -m backend.llm.compat groq "what time is it in Tokyo?"   # live round-trip
    python -m backend.llm.compat --selfcheck                        # no network
"""
from __future__ import annotations

import argparse
import asyncio
import json
import logging
import sys
from typing import Any, AsyncIterator

from .base import (
    DEFAULT_SYSTEM,
    MAX_TOKENS,
    Done,
    Error,
    Session,
    TextDelta,
    ToolCall,
    ToolSpec,
    ssl_context,
)
from .providers import base_url, card, credential_for, wire_names

log = logging.getLogger("nothal.compat")

# not-hal's OWN name for every request knob this adapter can send. What each provider CALLS them is
# the catalogue's business (`wire_names`, D44) — this adapter must never spell one itself, because
# it serves ten providers that share a wire and not a dialect. The selfcheck asserts every name
# here is spelled in the schema, so adding a knob without teaching the catalogue fails offline.
KNOBS = ("max_output_tokens", "effort", "temperature")

# OpenAI's client requires an Authorization header to exist even when the server ignores it,
# so a local runner (Ollama / LM Studio / llama.cpp) gets this rather than None.
LOCAL_PLACEHOLDER_KEY = "not-needed"

# Local-runner connection budget (see _client_once). A loopback server answers at once or is not
# there; 2 s is already generous. The read budget stays long — a local model may think for a
# while once it HAS answered — and matches the SDK's own default rather than httpx's 5 s.
LOCAL_CONNECT_S = 2.0
LOCAL_TIMEOUT_S = 600.0


def _error_kind(exc: Exception, offered_tools: bool = False) -> str:
    """Map an SDK exception to a shared Contract B Error kind (spec/20) by its TYPE and status
    code — never by matching the message prose (B-02).

    Same ladder as B1, and for the same reason: every provider here collapses context overflow
    and other bad requests into one 400, so a 400 maps to `unknown` (the generic apology)
    instead of a prose heuristic that mis-narrates. The OpenAI SDK's exception hierarchy is
    generated by the same tool as Anthropic's, so the shapes line up.

    `offered_tools` is the one refinement. Providers on this wire validate tool calls
    SERVER-side, so a model that emits a broken one (a name with the arguments glued onto it,
    say) is rejected before it can reach the parser in `converse`. Measured on
    groq/llama-3.3-70b with four tools offered: ~1 round in 3, and the same prompt composes a
    perfectly good call on a resample — so the recovery is a retry, and the tool loop already
    has one. It only fires on `malformed_tool_call`, hence this.

    The shape is the trap. The rejection arrives MID-STREAM, so the HTTP request logs 200 and
    the exception is a bare `APIError` with NO status code — not the 400 you would expect and
    not an `APIStatusError` at all. Both forms are mapped, since a provider that rejects before
    streaming would give the 400 instead. Still typed on (exception type, status code, whether
    tools were in play), reading no prose — B-02 holds. Being wrong costs one retried round: a
    mid-stream hiccup narrates as a bad tool call, and a retry was the right answer anyway.
    """
    import openai

    if isinstance(exc, openai.AuthenticationError):
        return "auth"
    if isinstance(exc, openai.RateLimitError):
        return "rate_limit"
    if isinstance(exc, openai.APIConnectionError):
        # Covers a local runner that simply isn't running — the commonest local failure.
        return "unavailable"
    if isinstance(exc, openai.NotFoundError):
        # 404: the model we were told to use is not there. Distinct from `unavailable` (the server
        # answered) and from `unknown` (we would be throwing away a precise, actionable cause and
        # narrating a shrug — the can't-rendered-as-didn't failure D36 fixed for tool calls).
        # Commonest cause by far is a model deleted from a local runner after being configured.
        # MUST precede the APIStatusError branch below: NotFoundError is a subclass of it.
        # A 404 could also be a wrong base-URL path, which is why the spoken line points at the
        # model SETTING rather than asserting the model was deleted.
        return "no_model"
    if isinstance(exc, openai.APIStatusError):
        if exc.status_code >= 500:
            return "unavailable"
        return "malformed_tool_call" if (offered_tools and exc.status_code == 400) else "unknown"
    if offered_tools and isinstance(exc, openai.APIError):
        # No status code: the stream was killed after a 200, which on a tools round is the
        # server rejecting its own model's tool call. APIConnectionError already returned above.
        return "malformed_tool_call"
    return "unknown"


def _tools_for_api(tools: list[ToolSpec]) -> list[dict]:
    """Contract T registry entries -> OpenAI function-tool objects.

    Translation lives in the adapter because it IS the provider's wire format, exactly like
    error mapping (spec/20). `shared/schemas/tools.json` spells the JSON-schema key `parameters`
    and carries a `tier` field, which is not-hal's safety business and not something to ship to
    a provider — so the registry entry is never passed through verbatim.
    """
    return [
        {
            "type": "function",
            "function": {
                "name": t["name"],
                "description": t.get("description", ""),
                "parameters": t.get("parameters") or {"type": "object", "properties": {}},
            },
        }
        for t in tools
    ]


class CompatModel:
    """B2. `converse` is an async generator, matching the ModelAdapter Protocol."""

    def __init__(
        self,
        provider: str,
        model: str | None = None,
        api_key: str | None = None,
        endpoint: str | None = None,
        effort: str | None = None,
        temperature: float | None = None,
    ):
        self.provider = provider
        self.card = card(provider)
        self.local = self.card.get("where") == "local"
        self.base_url = base_url(provider, endpoint)
        # No default model, by design: the adapter privileges none, and a turn with no model
        # yields a clean Error below rather than silently picking the first of some list. The
        # picker (settings) and the router choose the model; this class just uses what it is given.
        self.model = model
        self._api_key = api_key or credential_for(provider) or (
            LOCAL_PLACEHOLDER_KEY if self.local else None
        )
        self.effort = effort
        self.temperature = temperature
        self._client = None          # built on first use, then kept — see _client_once()

    def _client_once(self):
        """One client for this adapter's life, resting on Contract B's one-loop guarantee
        (spec/20). Same two costs avoided as in B1: a fresh TCP+TLS handshake per turn, and
        ~190 ms of CPU re-reading this machine's CA bundle (`ssl_context()` memoises it).

        `DefaultAsyncHttpxClient`, NOT a bare `httpx.AsyncClient`: the SDK passes a supplied
        client through verbatim, and a bare one silently swaps the SDK's 600 s read timeout for
        httpx's 5 s default — which would kill exactly the slow-first-token turns this exists to
        speed up. B1 records the same trap; it is a property of the SDK generator, not of either
        provider.

        A LOCAL runner gets no retries and a short CONNECT timeout (measured 2026-07-31). The
        SDK's two retries exist for transient cloud faults; a refused loopback socket is not
        transient — the server is simply not running, and it will not be running 1.4 s later
        either. Windows makes it worse by dropping rather than refusing, so each attempt waits
        out a timeout: dictation cleanup took **9.66 s** to discover a dead Ollama and fall back
        to pasting the raw transcript, all of it inside the paste path. Only the connect phase is
        shortened; the read timeout is untouched, because a local model may legitimately think
        for a long time once it HAS answered the socket.
        """
        import httpx
        import openai

        if self._client is None:
            kwargs: dict[str, Any] = {}
            http_kwargs: dict[str, Any] = {"verify": ssl_context()}
            if self.local:
                kwargs["max_retries"] = 0
                http_kwargs["timeout"] = httpx.Timeout(LOCAL_TIMEOUT_S, connect=LOCAL_CONNECT_S)
            self._client = openai.AsyncOpenAI(
                api_key=self._api_key,
                base_url=self.base_url,
                http_client=openai.DefaultAsyncHttpxClient(**http_kwargs),
                **kwargs,
            )
        return self._client

    def _kwargs(self, session: Session, utterance: str, tools: list[ToolSpec]) -> dict[str, Any]:
        # On this wire the system prompt is the first MESSAGE, not a separate parameter as it is
        # on Anthropic's. That is the whole message-shape difference between B1 and B2.
        messages: list[dict[str, Any]] = [
            {"role": "system", "content": session.system or DEFAULT_SYSTEM}
        ]
        messages += list(session.history)
        # An empty utterance is the tool-loop CONTINUE signal (spec/20): the tool results are
        # already in history (record_tool_round wrote them), so add no user turn.
        if utterance:
            messages.append({"role": "user", "content": utterance})

        # Structure — the shape of the wire itself, which is what this adapter IS. Below it, the
        # KNOBS, named in not-hal's vocabulary and spelled by the catalogue on the way out (D44).
        kwargs: dict[str, Any] = dict(model=self.model, messages=messages, stream=True)
        knobs: dict[str, Any] = {
            "max_output_tokens": session.max_tokens or MAX_TOKENS,   # transform lifts this
        }
        if not self.local:
            # Local servers vary on whether they accept this and a rejection costs the whole
            # turn, so usage (a latency-log nicety) is asked for only where it is reliable.
            kwargs["stream_options"] = {"include_usage": True}
        # On this wire "don't think" is not a separate switch — it is a VALUE of the effort
        # scale, so both intents leave through the same parameter. Each is gated on the card
        # declaring it: sending an effort a provider does not accept is rejected server-side and
        # costs the whole turn, and `"none"` is not universal (Ollama documents it, OpenAI's
        # declared scale does not include it). A provider that cannot say "don't think" simply
        # isn't told, and may think — spec/20 calls that a degradation, not an error.
        efforts = (self.card.get("capabilities", {}) or {}).get("effort")
        efforts = list(efforts) if isinstance(efforts, (list, tuple)) else []
        # Some providers REQUIRE a particular effort on any round that offers tools, and the card
        # names the value. OpenAI's reasoning models on /v1/chat/completions want `none`, and
        # OMITTING the parameter is not enough — the model reasons at its own default and the
        # request is rejected exactly the same way (measured 2026-08-03, with the request log:
        # we sent no `reasoning_effort` at all and still got "Function tools with reasoning_effort
        # are not supported"). Read the provider's own message literally: *set* it to none.
        #
        # Deliberately independent of `capabilities.effort`: that list is what the USER may pick,
        # and this is a value the PROVIDER demands. OpenAI's list has no "none" in it and should
        # not gain one — nobody should be able to choose this from the settings window.
        forced = self.card.get("tool_round_effort") if tools else None
        if forced is not None:
            knobs["effort"] = forced
        elif session.thinking is False and "none" in efforts:
            knobs["effort"] = "none"                     # beats the adapter's own effort
        elif self.effort and efforts:
            knobs["effort"] = self.effort
        # A per-call temperature (transform's determinism) overrides the adapter's own default.
        # Whether the provider HAS this knob is not asked here: `_spell` drops any knob the card
        # marks absent, which is how OpenAI — whose current models take no temperature — stops
        # receiving the stale `0.7` a stored profile still holds for it (found 2026-08-03).
        # Deliberately NOT gated on `capabilities.temperature`: that field drives which providers
        # show the CONTROL, and only the three local ones declare it, so gating here would have
        # silently taken deterministic cleanup away from Groq, which relies on temperature 0.
        temperature = session.temperature if session.temperature is not None else self.temperature
        if temperature is not None:
            knobs["temperature"] = temperature
        if tools:
            kwargs["tools"] = _tools_for_api(tools)
        kwargs.update(self._spell(knobs))
        return kwargs

    def _spell(self, knobs: dict[str, Any]) -> dict[str, Any]:
        """not-hal's knob names -> what THIS provider calls them (D44).

        Three outcomes, and the difference between the last two is the point:
        - a name: send it under that name;
        - `None` in the card: this provider HAS NO such knob, so drop it — a deliberate silence;
        - absent from the catalogue: a gap in `settings.json`, dropped and LOGGED. Guessing the
          neutral name would send an invented parameter, and a wrong parameter is rejected
          server-side and costs the whole turn — which is the exact failure this exists to end.
          Dropping degrades (the provider uses its own default); sending junk does not.
        """
        names = wire_names(self.provider)
        out: dict[str, Any] = {}
        for knob, value in knobs.items():
            if knob not in names:
                log.warning("%s: no wire name for %r in the catalogue — sending the request "
                            "without it (shared/schemas/settings.json > wire_names)",
                            self.provider, knob)
                continue
            if names[knob] is not None:
                out[names[knob]] = value
        return out

    async def converse(
        self,
        session: Session,
        utterance: str,
        tools: list[ToolSpec],
    ) -> AsyncIterator:
        if session.local_only and not self.local:
            yield Error("unavailable", f"B2/{self.provider} blocked: session is local_only")
            return
        if not self.base_url:
            yield Error("unknown", f"no endpoint for {self.provider!r}")
            return
        if not self._api_key:
            cred = self.card.get("credential", self.provider)
            yield Error("auth", f"no API key (keyring service 'not-hal', account {cred!r})")
            return
        if not self.model:
            yield Error("no_model", f"no model chosen for {self.provider!r}")
            return

        client = self._client_once()
        # index -> the call being assembled. This wire streams a tool call as FRAGMENTS: the id
        # and name arrive once, the arguments as a run of partial JSON strings that only parse
        # once concatenated. Anthropic hands over whole blocks instead, which is why B1 has no
        # equivalent of this bookkeeping.
        calls: dict[int, dict[str, str]] = {}
        usage: dict[str, int] | None = None

        sent = self._kwargs(session, utterance, tools)
        try:
            stream = await client.chat.completions.create(**sent)
            async for chunk in stream:
                if chunk.usage is not None:
                    usage = {
                        "input_tokens": chunk.usage.prompt_tokens,
                        "output_tokens": chunk.usage.completion_tokens,
                    }
                if not chunk.choices:
                    continue                      # the include_usage chunk carries no choices
                delta = chunk.choices[0].delta
                if delta is None:
                    continue
                if delta.content:
                    yield TextDelta(delta.content)
                for tc in delta.tool_calls or []:
                    slot = calls.setdefault(tc.index, {"id": "", "name": "", "args": ""})
                    if tc.id:
                        slot["id"] = tc.id
                    if tc.function is not None:
                        if tc.function.name:
                            slot["name"] = tc.function.name
                        if tc.function.arguments:
                            slot["args"] += tc.function.arguments

            for slot in calls.values():
                try:
                    parsed = json.loads(slot["args"] or "{}")
                except ValueError:
                    # The reserved kind, finally used: spec/20 anticipates exactly this on the
                    # OpenAI wire, where a small or local model can emit arguments that never
                    # parse. The retry spec/20 mentions belongs to the tool loop, not here.
                    yield Error(
                        "malformed_tool_call",
                        f"{slot['name'] or '?'} arguments are not JSON: {slot['args'][:200]!r}",
                    )
                    return
                yield ToolCall(slot["id"], slot["name"], parsed)
            yield Done(usage=usage)
        except Exception as exc:  # noqa: BLE001 - map every provider error to Error
            # SAY WHAT WE SENT. Three request-shape bugs in one night (max_tokens, temperature,
            # reasoning_effort) each cost a round of guessing because the log recorded the
            # provider's complaint and nothing about our own request. Names and scalar values
            # only — never `messages`, which is the user's speech, and never `tools`, which is
            # long and unchanging. Cheap, and only on the path that already failed.
            log.warning("%s/%s rejected the request; we sent: %s",
                        self.provider, self.model,
                        {k: v for k, v in sent.items() if k not in ("messages", "tools")}
                        | ({"tools": len(sent["tools"])} if "tools" in sent else {}))
            yield Error(_error_kind(exc, offered_tools=bool(tools)),
                        str(getattr(exc, "message", exc)))

    @staticmethod
    def record_tool_round(session: Session, assistant_text: str, calls, results: dict) -> None:
        """Append one completed tool round to `session.history` in OpenAI's wire shape, so the
        next converse round (driven with an empty utterance) sees the tool_calls and their results.
        Wire format, so it lives here like tool translation and error mapping; the orchestrator
        owns the loop and executes the tools (spec/20).

        `results` maps a tool_call id -> its result string. This wire wants ONE assistant message
        carrying the `tool_calls` array, then ONE `tool` message per result — the mirror of B1's
        single tool_result user message."""
        session.history.append({
            "role": "assistant",
            "content": assistant_text or None,
            "tool_calls": [
                {"id": c.id, "type": "function",
                 "function": {"name": c.name, "arguments": json.dumps(c.input)}}
                for c in calls
            ],
        })
        for c in calls:
            session.history.append(
                {"role": "tool", "tool_call_id": c.id, "content": results.get(c.id, "")})


async def _run(provider: str, question: str, model: str | None) -> int:
    adapter = CompatModel(provider, model=model)
    print(f"[{provider} -> {adapter.base_url} model={adapter.model}]", file=sys.stderr)
    status = 0
    async for ev in adapter.converse(Session(id="cli"), question, []):
        if isinstance(ev, TextDelta):
            print(ev.text, end="", flush=True)
        elif isinstance(ev, ToolCall):
            print(f"\n[tool_call {ev.name} {ev.input}]", flush=True)
        elif isinstance(ev, Done):
            print(f"\n[done: {ev.usage}]")
        elif isinstance(ev, Error):
            print(f"\n[error/{ev.kind}: {ev.detail}]", file=sys.stderr)
            status = 1
    return status


def _selfcheck() -> None:
    # No network anywhere in here: every assertion is about request shaping, error mapping and
    # client lifetime. The one thing a live run adds is proof the provider agrees, which is what
    # `python -m backend.llm.compat groq "..."` is for.
    import time

    import openai

    def _exc(cls, status=None):
        e = cls.__new__(cls)
        if status is not None:
            e.status_code = status
        return e

    # Error mapping is by exception TYPE and status code, never message prose (B-02).
    assert _error_kind(_exc(openai.AuthenticationError)) == "auth"
    assert _error_kind(_exc(openai.RateLimitError)) == "rate_limit"
    assert _error_kind(_exc(openai.APIConnectionError)) == "unavailable"
    assert _error_kind(_exc(openai.InternalServerError, 500)) == "unavailable"
    assert _error_kind(_exc(openai.BadRequestError, 400)) == "unknown", \
        "a 400 must map to the generic apology — no prose-guessing at 'context' (B-02)"
    # A 404 is neither a 5xx nor a shrug: the cause is precise and actionable, so it gets
    # its own kind describing the error rather than the generic apology.
    assert _error_kind(_exc(openai.NotFoundError, 404)) == "no_model", "a bad model id is nameable"
    assert _error_kind(RuntimeError("boom")) == "unknown"

    # ...except on a round that OFFERED tools, where a 400 is the provider rejecting its own
    # model's broken tool call server-side (D36). It becomes the kind the tool loop retries.
    # A 404 is the model we were told to use not being there — commonly one deleted from a local
    # runner after it was configured. It must NOT fall through to `unknown`: Ollama tells us the
    # exact cause and a shrug would throw that away. NotFoundError subclasses APIStatusError, so
    # this also pins the ORDER of the ladder — put the generic branch first and this silently
    # regresses to `unknown` with every test still green except this one.
    assert _error_kind(_exc(openai.NotFoundError, 404)) == "no_model"
    assert _error_kind(_exc(openai.BadRequestError, 400)) == "unknown", \
        "a plain 400 stays generic — only 404 carries the model-not-found meaning"
    assert _error_kind(_exc(openai.BadRequestError, 400), offered_tools=True) == "malformed_tool_call"
    assert _error_kind(_exc(openai.BadRequestError, 400), offered_tools=False) == "unknown", \
        "no tools offered means a 400 cannot be a bad tool call"
    # Offering tools must not swallow the kinds that are about the CONNECTION, not the call.
    assert _error_kind(_exc(openai.InternalServerError, 500), offered_tools=True) == "unavailable"
    assert _error_kind(_exc(openai.AuthenticationError), offered_tools=True) == "auth"
    assert _error_kind(_exc(openai.RateLimitError), offered_tools=True) == "rate_limit"
    assert _error_kind(_exc(openai.NotFoundError, 404), offered_tools=True) == "no_model", \
        "a bad model id stays a bad model id — only 400 is the tool-call signal"
    # The shape actually observed on groq: mid-stream rejection, so a bare APIError with NO
    # status code (the HTTP request logged 200). This is the case that matters in practice.
    assert not hasattr(_exc(openai.APIError), "status_code"), "the fixture must carry no status"
    assert _error_kind(_exc(openai.APIError), offered_tools=True) == "malformed_tool_call"
    assert _error_kind(_exc(openai.APIError), offered_tools=False) == "unknown"
    # A dropped connection is still a dropped connection, tools or not — it must not be
    # swallowed by the branch above, which it would be (APIConnectionError extends APIError).
    assert _error_kind(_exc(openai.APIConnectionError), offered_tools=True) == "unavailable"
    assert _error_kind(_exc(openai.APITimeoutError), offered_tools=True) == "unavailable"

    # Tool translation: the registry's OWN entries must survive it, since that is the shape the
    # model will really be handed. `tier` is not-hal's business and must never reach a provider.
    from shared.config import load_schemas

    registry = load_schemas()["tools"]["tools"]
    assert registry, "shared/schemas/tools.json must carry the starter tools"
    assert any("tier" in t for t in registry), "the registry is expected to carry tiers"
    wired = _tools_for_api(registry)
    assert len(wired) == len(registry)
    for w, t in zip(wired, registry):
        assert w["type"] == "function"
        assert w["function"]["name"] == t["name"]
        assert "tier" not in w and "tier" not in w["function"], "tier must not leave the machine"
        assert w["function"]["parameters"] == t["parameters"], \
            "the registry's `parameters` IS the JSON schema on this wire"
    assert _tools_for_api([{"name": "bare"}])[0]["function"]["parameters"] == \
        {"type": "object", "properties": {}}, "a tool with no parameters must still be valid JSON schema"

    # Request shaping. The system prompt is a MESSAGE here, not a parameter (the one real
    # difference from B1), and history must sit between it and the new utterance.
    groq = CompatModel("groq", model="m", api_key="x")
    s = Session(id="t", history=[{"role": "user", "content": "before"},
                                {"role": "assistant", "content": "reply"}])
    k = groq._kwargs(s, "now", [])
    assert k["messages"][0]["role"] == "system" and k["messages"][0]["content"] == DEFAULT_SYSTEM
    assert [m["content"] for m in k["messages"][1:]] == ["before", "reply", "now"], k["messages"]
    assert k["stream"] is True, "adapters MUST stream (spec/20)"
    assert k["stream_options"] == {"include_usage": True}, "cloud turns should report usage"
    assert "tools" not in k, "no tools key at all when the list is empty"
    assert "reasoning_effort" not in k, "effort must not be sent unasked"

    # D44 — this adapter serves ten providers that share a wire and not a dialect, so it names
    # knobs in not-hal's vocabulary and the catalogue spells them. Every knob it can emit must be
    # spelled for the wire, or a request silently goes out missing it.
    from .providers import schema as _settings_schema
    _wire_default = _settings_schema().get("wire_names", {}).get("openai", {})
    for _knob in KNOBS:
        assert _knob in _wire_default, \
            f"{_knob!r} has no wire name — add it to settings.json > wire_names.openai"
    assert k["max_tokens"] == MAX_TOKENS, "the classic spelling is the wire's default"

    # ...and OpenAI, which renamed it. This is the bug that produced the rule: `max_tokens` was
    # sent to everybody and every assistant turn on gpt-5.6-sol was rejected outright.
    oai = CompatModel("openai", model="m", api_key="x", temperature=0.7)
    ko = oai._kwargs(Session(id="t"), "q", [])
    assert ko["max_completion_tokens"] == MAX_TOKENS and "max_tokens" not in ko, sorted(ko)
    # `null` in a card means the provider HAS NO such knob — dropped, not renamed. OpenAI's
    # current models take no temperature, and a stored profile still holds 0.7 for it.
    assert "temperature" not in ko, "a knob a card marks absent must not go out"
    assert "temperature" in CompatModel("groq", model="m", api_key="x", temperature=0.7)._kwargs(
        Session(id="t"), "q", []), "...but the providers that DO have it must still get it"
    # A knob nobody spelled is dropped and logged, never guessed: an invented parameter is
    # rejected server-side and costs the whole turn, which is what this rule exists to stop.
    assert oai._spell({"no_such_knob": 1}) == {}, "an unspelled knob must not be guessed at"

    # A card may DEMAND a particular effort on any round offering tools. OpenAI's reasoning models
    # want "none" there, and omitting the parameter is not the same thing — the model reasons at
    # its own default and the request is rejected identically. Only on tool rounds: a plain answer
    # keeps the user's dial.
    _tool = [{"name": "t", "description": "d", "parameters": {"type": "object", "properties": {}}}]
    oe = CompatModel("openai", model="m", api_key="x", effort="high")
    assert oe._kwargs(Session(id="t"), "q", [])["reasoning_effort"] == "high", "kept without tools"
    assert oe._kwargs(Session(id="t"), "q", _tool)["reasoning_effort"] == "none", \
        "a tool round must SET the demanded effort, not omit the parameter"
    # The demanded value is NOT in the card's `capabilities.effort` and must not need to be —
    # that list is the user's menu, this is the provider's requirement.
    assert "none" not in (card("openai").get("capabilities", {}) or {}).get("effort", []), \
        "'none' must stay out of the picker's choices for OpenAI"
    # ...and a provider that demands nothing is untouched by the rule.
    og = CompatModel("ollama", model="m", effort="high")
    assert og._kwargs(Session(id="t"), "q", _tool)["reasoning_effort"] == "high", \
        "only the cards that demand an effort override it on a tool round"
    assert groq._kwargs(Session(id="t", system="custom"), "q", [])["messages"][0]["content"] == \
        "custom", "a session system prompt must win over the default"

    # Tool-loop continue signal: an empty utterance adds NO user message (the tool results are
    # already in history), so two user turns never stack up.
    kc = groq._kwargs(Session(id="t", history=[{"role": "user", "content": "q"}]), "", [])
    assert [m["role"] for m in kc["messages"]] == ["system", "user"], kc["messages"]

    # Tool-loop threading (spec/20): a completed round serialises in OpenAI's wire shape — one
    # assistant message carrying the tool_calls array, then one `tool` message per result.
    st = Session(id="t")
    CompatModel.record_tool_round(
        st, "checking", [ToolCall("c1", "system_status", {"x": 1})], {"c1": "noon"})
    assert st.history[0]["role"] == "assistant" and st.history[0]["content"] == "checking"
    assert st.history[0]["tool_calls"][0]["id"] == "c1"
    assert json.loads(st.history[0]["tool_calls"][0]["function"]["arguments"]) == {"x": 1}
    assert st.history[1] == {"role": "tool", "tool_call_id": "c1", "content": "noon"}

    # Effort is only sent where the card declares it — Groq's capabilities are empty, so asking
    # for effort there must NOT put an unsupported parameter on the wire.
    assert "reasoning_effort" not in CompatModel("groq", model="m", api_key="x", effort="high") \
        ._kwargs(Session(id="t"), "q", [])
    assert CompatModel("openai", model="m", api_key="x", effort="high") \
        ._kwargs(Session(id="t"), "q", [])["reasoning_effort"] == "high", \
        "OpenAI declares an effort capability, so it must be sent"

    # `thinking=False` (every transform sets it) rides out on the SAME parameter, because on this
    # wire "off" is a value of the effort scale — but only where the card lists `none`.
    fake = {"capabilities": {"effort": ["none", "low", "high"]}, "wire": "openai",
            "where": "local", "endpoint": "127.0.0.1:1"}
    thinker = CompatModel("ollama", model="m", effort="high")
    thinker.card = fake
    kw = thinker._kwargs(Session(id="t", thinking=False), "q", [])
    assert kw["reasoning_effort"] == "none", "thinking=False must beat the adapter's own effort"
    assert thinker._kwargs(Session(id="t"), "q", [])["reasoning_effort"] == "high", \
        "an unset `thinking` must leave the configured effort alone"
    # A provider whose scale has no `none` must NOT be sent one — a rejected value costs the turn.
    noneless = CompatModel("openai", model="m", api_key="x")
    assert "none" not in (noneless.card.get("capabilities", {}).get("effort") or []), \
        "guard assumes OpenAI's declared scale still lacks `none`"
    assert "reasoning_effort" not in noneless._kwargs(Session(id="t", thinking=False), "q", []), \
        "don't-think must be withheld where the card cannot express it"
    # ...and a card with no effort at all stays silent on both paths.
    assert "reasoning_effort" not in CompatModel("groq", model="m", api_key="x") \
        ._kwargs(Session(id="t", thinking=False), "q", [])

    # A local runner: no key needed, no usage request, temperature allowed.
    olla = CompatModel("ollama", model="m", temperature=0.4)
    assert olla.local and olla.base_url == "http://127.0.0.1:11434/v1"
    assert olla._api_key == LOCAL_PLACEHOLDER_KEY, "a local runner must not demand a stored key"
    lk = olla._kwargs(Session(id="t"), "q", [])
    assert "stream_options" not in lk, "local servers are not all willing to report usage"
    assert lk["temperature"] == 0.4

    # Guard rails, each returning a mapped Error rather than raising.
    async def first(model, session=None):
        async for ev in model.converse(session or Session(id="t"), "q", []):
            return ev

    err = asyncio.run(first(CompatModel("groq", model="m", api_key="x"),
                            Session(id="t", local_only=True)))
    assert isinstance(err, Error) and err.kind == "unavailable", err
    # ...but a LOCAL provider must serve a local_only session: that is the whole point of B2's
    # local half, and refusing here would make M2's privacy mode unimplementable.
    ok = asyncio.run(first(CompatModel("ollama", model="m"), Session(id="t", local_only=True)))
    assert not (isinstance(ok, Error) and "local_only" in ok.detail), \
        "a local runner must accept a local_only session"
    assert asyncio.run(first(CompatModel("groq", api_key="x"))).kind == "no_model", \
        "no model chosen must be reported as such, not sent as model=None nor shrugged at"
    # Two legitimate outcomes, depending on whether this machine holds a Groq key: `auth` with no
    # key at all (CI), `no_model` where a key exists and the call actually reaches Groq, which
    # answers 404 for the bogus model id. The second is live confirmation that the 404 mapping is
    # not Ollama-specific — Groq returns the same shape for a model that isn't there.
    assert asyncio.run(first(CompatModel("groq", model="m", api_key=None))).kind in \
        ("auth", "no_model")

    # Client lifetime (spec/20). No network: every cost here is local CPU.
    assert ssl_context() is ssl_context(), "the CA bundle must be parsed once per process"
    first_client = groq._client_once()
    assert groq._client_once() is first_client, "the client must be built once and kept"
    t0 = time.perf_counter()
    CompatModel("groq", model="m", api_key="x")._client_once()
    build_ms = (time.perf_counter() - t0) * 1000
    assert build_ms < 50, f"building the client took {build_ms:.0f} ms — CA bundle reloaded?"

    # A dead local runner must fail FAST, inside the paste path (measured 9.66 s before this).
    # A cloud provider keeps the SDK's retries, because its faults really are transient.
    local = CompatModel("ollama", model="m")
    assert local._client_once().max_retries == 0, "a refused loopback socket must not be retried"
    assert groq._client_once().max_retries > 0, "cloud turns keep their transient-fault retries"
    assert local._client_once().timeout.connect <= 5, "a local connect must not wait out a drop"
    assert local._client_once().timeout.read >= 60, \
        "a local model may think for a while once it HAS answered — only connect is shortened"
    # ...and the URL it will dial must already be IPv4, or the connect budget is spent on ::1.
    assert "127.0.0.1" in str(local._client_once().base_url), \
        f"local base_url must not resolve via localhost: {local._client_once().base_url}"

    assert first_client.timeout.read >= 60, \
        f"custom client dropped the SDK read timeout: {first_client.timeout}"
    assert str(first_client.base_url).rstrip("/") == groq.base_url.rstrip("/")

    # Every catalogue provider on this wire must be constructible — that is what `adapter: true`
    # promises the settings window, and a card missing an api/endpoint would break it silently.
    from .providers import catalog, wire

    served = [p for p, c in catalog().items() if c.get("adapter") and wire(p) == "openai"]
    assert served, "no provider is wired to B2 — check `adapter` in settings.json"
    for pid in served:
        assert CompatModel(pid, model="m", api_key="x").base_url, f"{pid}: no reachable base URL"

    print(f"selfcheck OK: {len(served)} providers on one adapter, tool translation drops `tier`, "
          "system-as-message, effort gated by capability, every knob spelled by the catalogue "
          "and none by this adapter (D44), error mapping by type/status, "
          "client built once with the long read timeout intact")


def main() -> None:
    ap = argparse.ArgumentParser(description="not-hal B2 OpenAI-compatible adapter (spec/20)")
    ap.add_argument("provider", nargs="?", help="catalogue id: groq, openai, ollama, …")
    ap.add_argument("question", nargs="?", help="prompt to send")
    ap.add_argument("--model", default=None, help="model id (required for cloud providers)")
    ap.add_argument("--selfcheck", action="store_true", help="offline logic check, no network")
    args = ap.parse_args()

    if args.selfcheck:
        _selfcheck()
        return
    if not args.provider or not args.question:
        ap.error("provide a provider and a question, or --selfcheck")
    sys.exit(asyncio.run(_run(args.provider, args.question, args.model)))


if __name__ == "__main__":
    main()
